"""Exceptions package"""
from .exceptions import (
    APIException,
    ValidationError,
    AuthenticationError,
    TokenExpiredError,
    InvalidTokenError,
    AuthorizationError,
    NotFoundError,
    DuplicateError,
    RateLimitError,
    DatabaseError,
    DuplicateEntryError,
    ServiceError,
    ConfigurationError,
    InternalServerError,
    BusinessLogicError,
    InsufficientDataError,
    InvalidStateError,
    OperationNotAllowedError,
)

__all__ = [
    'APIException',
    'ValidationError',
    'AuthenticationError',
    'TokenExpiredError',
    'InvalidTokenError',
    'AuthorizationError',
    'NotFoundError',
    'DuplicateError',
    'RateLimitError',
    'DatabaseError',
    'DuplicateEntryError',
    'ServiceError',
    'ConfigurationError',
    'InternalServerError',
    'BusinessLogicError',
    'InsufficientDataError',
    'InvalidStateError',
    'OperationNotAllowedError',
]
